extensions:
  health_check:
    endpoint: "0.0.0.0:13133"  # Par défaut
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: localhost:15680

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: localhost:4317
      http:
        endpoint: localhost:4318
    
processors:

  memory_limiter:
    # 75% of maximum memory up to 2G
    limit_mib: 1536
    # 25% of limit up to 2G
    spike_limit_mib: 512
    check_interval: 5s

  batch:

  # Ajout de l'ID d'application pour les traces envoyées par Java
  attributes/add_app_id_java:
    actions:
      - action: insert
        key: nudge_application_id
        value: 95776b60-b22d-4b95-801b-4137a6ee1f98
    include:
      # strict ou regexp
      match_type: strict
      # attributes ou resources
      resources:
        - key: telemetry.sdk.language
          value: java
        - key: service.name
          value: petclinic

  # Ajout de l'ID d'application pour les traces envoyées par NodeJS
  attributes/add_app_id_node:
    actions:
      - action: insert
        key: nudge_application_id
        value: be6abaf9-ba97-4483-b502-24110c805270
    include:
      # strict ou regexp
      match_type: strict
      # attributes ou resources
      resources:
        - key: telemetry.sdk.language
          value: nodejs

exporters:
  debug:
    verbosity: Detailed
  nudgedebug:
    verbosity: Detailed
  nudgehttp:
    # endpoint de Nudge
    endpoint: https://ph-apm.dev.atakama-technologies.com
    # Il est possible de laisser la valeur par defaut si non définie dans la partie processor
    app_id: 00000000-0000-0000-0000-000000000000
    # chemin de la requete http, par defaut /collect/rawdata
    pathCollect: /collect/rawdata
    # methode http pour le flush des rawdatas
    method: PUT
    # encodage du rawadata. proto, json
    encoding: proto # -> application/x-protobuf
    # chemin de la requette http des pages personnelles de NudgeExorter
    debug_path: /debug/NudgeExporter
    # Port de page personnelle de NudgeExorter
    debug_port: 15682
    # Enregistrement du rawdata brut sur disque
    recordCollecte: true
    # Insertion des métriques resources (disque, memoire, cpu)
    insertResource: true
    # Timeout du Buffer Transaction en secondes
    timeoutBufferTransaction: 60
    # Prefixe nom du service s'affiche dans la map, par defaut NodeJS_1
    prefixeServiceName: NodeJS_1
    # Nom de l'application et du serveur, inseré dans le rawdata, par defaut APP_CCC
    applicationName: APP_CCC
    # Ajout ou pas pour des raison de sécurité du login de connexion à une base de donnée
    sendUserConnectionString: true
    # Temps en minutes de rafraichissement des lecteurs physiques & logiques (CF : Worker.js), par defaut 10
    refreshScanDrives: 60
    # Temps refresh en secondes pour le calcul de la charge CPU, par defaut 5s
    refreshLoadCPU: 30
    # Attend la fin de la trace (parentSpanId == empty) avant de faire le flush vers le rawdata, par defaut true
    waitEndService: true
    nodeJS:
      # Fonction inconnue
      # UnknownFunction=UnknownFunction, par defaut F?
      unknownFunction: F?
      # Classe inconnue
      # UnknownClass=UnknownClass, par defaut C?
      unknownClass: C?
    console:
      verbosity: Detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, attributes/add_app_id_java, attributes/add_app_id_node, batch]
      #processors: [memory_limiter, batch]
      exporters: [nudgehttp, nudgedebug]
    metrics:
      receivers: [otlp]
      # processors: [memory_limiter, add_app_id_java, add_app_id_node, batch]
      processors: [memory_limiter, batch]
      exporters: [nudgehttp, nudgedebug]
    logs:
      receivers: [otlp]
      # processors: [memory_limiter, add_app_id_java, add_app_id_node, batch]
      processors: [memory_limiter, batch]
      exporters: [nudgehttp, nudgedebug]

  # zpages:
  # http://127.0.0.1:15680/debug/servicez
  # http://127.0.0.1:15680/debug/tracez
  # http://localhost:15680/debug/pipelinez
  # http://localhost:15680/debug/extensionz
  # http://localhost:15680/debug/featurez
  # http://localhost:15680/debug/expvarz
  # pprof:
  # http://localhost:1777/debug/pprof/
  # http://localhost:1777/debug/pprof/heap
  # http://localhost:1777/debug/pprof/profile
  # http://localhost:1777/debug/pprof/goroutine
  # http://localhost:1777/debug/pprof/threadcreate
  # http://localhost:1777/debug/pprof/block
  # http://localhost:1777/debug/pprof/cmdline
  # http://localhost:1777/debug/pprof/symbol
  # http://localhost:1777/debug/pprof/trace
  # http://localhost:1777/debug/pprof/trace?seconds=5
  # http://localhost:1777/debug/pprof/trace?seconds=5&debug=1
  # health_check:
  # http://localhost:13133
  extensions: [health_check, pprof, zpages]