extensions:
  zpages:
    # http://127.0.0.1:15680/debug/servicez
    endpoint: localhost:15680

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: localhost:4317
      http:
        endpoint: localhost:4318
    
processors:

  memory_limiter:
    # 75% of maximum memory up to 2G
    limit_mib: 1536
    # 25% of limit up to 2G
    spike_limit_mib: 512
    check_interval: 5s

  batch:

  # add_app_id_java:  # <-- alias
  #   type: attributes
  #   attributes:
  #     - action: insert
  #       key: nudge_application_id
  #       value: 95776b60-b22d-4b95-801b-4137a6ee1f98
  #   include:
  #     match_type: strict
  #     resource_attributes:
  #       - key: telemetry.sdk.language
  #         value: java
  # add_app_id_node:  # <-- alias
  #   type: attributes
  #   attributes:
  #     - action: insert
  #       key: nudge_application_id
  #       value: be6abaf9-ba97-4483-b502-24110c805270
  #   include:
  #     match_type: strict
  #     resource_attributes:
  #       - key: telemetry.sdk.language
  #         value: nodejs

exporters:
  debug:
    verbosity: Detailed
  nudgedebug:
    verbosity: Detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      # processors: [memory_limiter, add_app_id_java, add_app_id_node, batch]
      processors: [memory_limiter, batch]
      exporters: [nudgedebug]
    metrics:
      receivers: [otlp]
      # processors: [memory_limiter, add_app_id_java, add_app_id_node, batch]
      processors: [memory_limiter, batch]
      exporters: [nudgedebug]
    logs:
      receivers: [otlp]
      # processors: [memory_limiter, add_app_id_java, add_app_id_node, batch]
      processors: [memory_limiter, batch]
      exporters: [nudgedebug]

  # http://127.0.0.1:15680/debug/servicez
  # http://127.0.0.1:15680/debug/tracez
  extensions: [zpages]